server:
  port: 1234
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laba1002?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis:
  #  mapper???????
  mapper-locations: classpath:/mybatis/mapper/*.xml
  #  ????????
  type-aliases-package: com.example.laba1002.pojo